name: Publish Docker image
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            ranobenet/ranobenetapi
          tags: |
            type=sha,prefix=

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./RanobeNet/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
