name: build

on:
  push:
  pull_request:
    branches: [main]
    paths:
      - "**.cs"
      - "**.csproj"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal --logger trx --results-directory "TestResults"
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-results
          path: TestResults
        # always() を使用して常にこのステップを実行し、テストが失敗したときにテスト結果を公開する
        if: ${{ always() }}
      - name: Install tools
        run: dotnet tool restore
      - name: Create swagger.json
        run: dotnet swagger tofile --output ../swagger.json ./bin/Release/net6.0/RanobeNet.dll v1
        working-directory: ./RanobeNet
      - name: Upload swagger.json
        uses: actions/upload-artifact@v2
        with:
          name: swagger
          path: swagger.json
