name: Test and Publish package

on:
  push:
  pull_request:
    branches: [main]
    paths:
      - "**.cs"
      - "**.csproj"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal --logger trx --results-directory "TestResults"
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v2
        with:
          name: TestResults
          path: TestResults
        # always() を使用して常にこのステップを実行し、テストが失敗したときにテスト結果を公開する
        if: ${{ always() }}
      - name: Create Firebase credentials
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: |
          echo "$FIREBASE_CREDENTIALS" > ./RanobeNet/firebase_credentials.json
      - name: Install tools
        run: dotnet tool restore
      - name: Create swagger.json
        run: dotnet swagger tofile --output ../swagger.json ./bin/Release/net6.0/RanobeNet.dll v1
        working-directory: ./RanobeNet
      - name: Upload swagger.json
        uses: actions/upload-artifact@v2
        with:
          name: swagger
          path: swagger.json
      - name: Remove Firebase credentials
        run: |
          rm ./RanobeNet/firebase_credentials.json
      - name: Publish
        run: dotnet publish --configuration Release --no-build
      - name: Upload RanobeNet Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: RanobeNet
          path: ./RanobeNet/bin/Release/net6.0/publish/
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        with:
          files: swagger.json
